routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('article/{id}', 'ArticleController@show')->name('article');

Route::get('/', 'ArticleController@list')->name('articlelist');

Route::get('home/{id}', 'HomeController@show')->name('user');

/*AUTH ROUTES*/
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
/*ROUTE POUR AFFICHER LA LIST DES ARTICLES DANS HOME(USER SPACE)*/ 
Route::get('/home', 'HomeController@list')->name('articlelist');

Route::resource('crud', 'CrudController');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
        'title',
        'extract',
        'content',
        'image',
        'author_id'
      ];
    
    public function author()
    {
        return $this->belongsTo('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Article;
class ArticleController extends Controller
{
    public function show($id)
    {
        $article = Article::findOrFail($id);
        return view('article', ['article' => $article]);
    }


    public function list()
    {
        $articles = Article::All()
        ->sortByDesc("publish_date");
        return view('articles', ['articles' =>$articles]);
    }
    
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CrudController.php
<?php

namespace App\Http\Controllers;
use App\Article;
use Illuminate\Http\Request;

class CrudController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('crud/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title'=>'required',
            'extract'=>'required',
            'content'=>'required',
            'image'=>'required'
          ]);
          $crud = new Article([
            'title' => $request->get('title'),
            'extract' => $request->get('extract'),
            'content' => $request->get('content'),
            'image' => $request->get('image'),
            'author_id' => auth()->id()
          ]);
          $crud->save();
          return redirect('/crud')->with('success', 'Article has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;
use App\Article;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('/home');
    }
    
    public function list()
    {
        $user = Auth::user();
        $articles = Article::where('author_id', $user->id)->get();
        return view('home', ['articles' =>$articles]);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    public function show($id)
    {
        return view('/home', ['user' => User::findOrFail($id)]);
    }
    
}

resources/views/article.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/article.css') }}">
    <title>Document</title>
</head>
<body>

    <section class="container">
        <div class="card">
                <div class="card-body">
                    <div class="title-return-login">
                            <a href="/"><input type="button" class="btn-return" value="RETURN"></a>
                            <h3 class="card-title text-center">{{$article->title}}</h3> 
                            <a href="#"><input type="button" class="btn-login" value="LOGIN"></a>  
                    </div>
                        <img class="card-img-top" src="{{$article->image}}" alt="">
                        <hr class="my-4">
                        <p class="card-text text-right">Published : {{$article->publish_date}}</p>
                        <hr class="my-4">
                        <p class="card-text">{{$article->content}}</p>
                        <footer class="blockquote-footer text-right">
                            <cite>{{$article->author->username}}</cite>
                        </footer>
                </div>
            </div>    
    </section>
 
</body>
</html>

resources/views/articles.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <title>Document</title>
</head>
<body>
    <header class="header_index">
        <h3 class="title_header_index">BLOG WITH LARAVEL</h3>
        <a href="{{ route('login') }}"><input type="button" class="login_header_index" value="LOGIN"></a>  
    </header>
    <section class="container">
        <div class="card-columns">
                @foreach ( $articles as $article )
                <a href="{{route('article',['id' => $article->id])}}">
                    <div class="card">
                        <div class="card-body">
        
                                <h3 class="card-title text-center">{{$article->title}}</h3>
                                <img class="card-img-top" src="{{$article->image}}" alt="">
                                <p class="card-text text-justify">{{$article->extract}}</p>
                                <hr class="my-4">
                                <p class="card-text text-left">Published : {{$article->publish_date}}</p>
                                <footer class="blockquote-footer">
                                    <cite>{{$article->author->username}}</cite>
                                </footer>
                        </div>
                    </div>    
                </a> 
                @endforeach       
        
        </div>
    </section>
</body>
</html>

resources/views/crud/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
        <div class="row justify-content-center">
        <div class="card">
                <div class="card-header">
                  Add Article
                </div>
                <div class="card-body">
                  @if ($errors->any())
                    <div class="alert alert-danger">
                      <ul>
                          @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                          @endforeach
                      </ul>
                    </div><br />
                  @endif
                    <form method="post" action="{{ route('crud.store') }}">
                        <div class="form-group">
                            @csrf
                            <label for="title">Title:</label>
                            <input type="text" class="form-control" name="title"/>
                        </div>
                        <div class="form-group">
                            <label for="extract">Extract :</label>
                            <input type="text" class="form-control" name="extract"/>
                        </div>
                        <div class="form-group">
                              <label for="content">Content :</label>
                              <textarea class="form-control" name="content" id="content" cols="30" rows="5"></textarea>
                          </div>
                          <div class="form-group">
                                  <label for="image">Image Link :</label>
                                  <input type="text" class="form-control" name="image"/>
                              </div>
                        
                        <button type="submit" class="btn btn-primary">Add</button>
                    </form>
                </div>
              </div>
</div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                        @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <h3 class="text-center">WELCOME {{ Auth::user()->username }}</h3>
                    <p class="text-center">You are logged in!</p>

                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
            
        </div>
    </div>
</div>

<section class="container">
        <div class="card-columns">
                @foreach ( $articles as $article )
                
                    <div class="card">
                        <div class="card-body">
        
                                <h3 class="card-title text-center">{{$article->title}}</h3>
                                <img class="card-img-top" src="{{$article->image}}" alt="">
                                <p class="card-text text-justify">{{$article->extract}}</p>
                                <hr class="my-4">
                                <p class="card-text text-left">Published : {{$article->publish_date}}</p>
                                <footer class="blockquote-footer">
                                    <cite>{{$article->author->username}}</cite>
                                </footer>
                        </div>
                    </div>    
                
                @endforeach       
        
        </div>
    </section>

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>BLOG • {{ Auth::user()->username }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/auth.css') }}">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    <p>BLOG WITH LARAVEL</p>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        <li class="nav-item">
                            <a href="{{ url('/') }}"><input type="button" class="btn-login" value="{{ __('HOME') }}"></a>  
                        </li>
                            <li class="nav-item">
                                <a href="{{ route('login') }}"><input type="button" class="btn-login" value="{{ __('LOGIN') }}"></a>  
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a href="{{ route('register') }}"><input type="button" class="btn-register" value="{{ __('REGISTER') }}"></a>  
                                </li>
                            @endif
                        @else
                        <li class="nav-item">
                                <a href="{{ url('/home') }}"><input type="button" class="btn-login" value="{{ __('HOME') }}"></a>  
                            </li>

                        <li class="nav-item">
                                <a href="{{ route('crud.create') }}"><input type="button" class="btn-login" value="{{ __('ADD AN ARTICLE') }}"></a>  
                            </li>

                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->username }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>BLOG </title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/auth.css') }}">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    <p>BLOG WITH LARAVEL</p>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        <li class="nav-item">
                            <a href="{{ url('/') }}"><input type="button" class="btn-login" value="{{ __('HOME') }}"></a>  
                        </li>
                            <li class="nav-item">
                                <a href="{{ route('login') }}"><input type="button" class="btn-login" value="{{ __('LOGIN') }}"></a>  
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a href="{{ route('register') }}"><input type="button" class="btn-register" value="{{ __('REGISTER') }}"></a>  
                                </li>
                            @endif
                        @else
                        <li class="nav-item">
                                <a href="{{ route('login') }}"><input type="button" class="btn-login" value="{{ __('ADD AN ARTICLE') }}"></a>  
                            </li>

                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->username }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>